# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='user',
        ),
        migrations.AddField(
            model_name='trips',
            name='plan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
