# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_project', '0002_auto_20170927_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planned_to', to='dojo_project.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trips',
            name='end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
